image: sam0verfl0w/liboftp:latest
  
stages:
  - lint
  - build
  - test
  - release
  - cleanup

cache:
  paths:
    - build/
    - subprojects/

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.infra.vsf >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git submodule update --init --remote
    #- apt-get update && apt-get install ssh python3 python3-pip python3-venv openssl libssl-dev libbsd-dev -y
    #- python3 -m venv . && source ./bin/activate && pip install meson ninja

include:
  - local: '.gitlab/lint.yml'
  - local: '.gitlab/build.yml'
  - local: '.gitlab/test.yml'
  - local: '.gitlab/release.yml'
  - local: '.gitlab/cleanup.yml'

