repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-xml
    -   id: check-case-conflict
    -   id: check-added-large-files

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["-i", "-style=file"]
        files: "(src/.*\\.c$|inc/.*\\.h$)"
        pass_filenames: true

  - repo: local
    hooks:
      - id: git-add
        name: Automatically add formatted files
        entry: git add
        language: system
        types: [text]
        stages: [manual]
        pass_filenames: true

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: ["-p=build"]
        files: "^src/.*\\.c$|^inc\\/.*\\.h$"
